import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Russo_One } from 'next/font/google'

const russoOne = 
Russo_One({ 
  weight: '400', 
  subsets: ['latin'] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={russoOne.className}>
        {children}
      </body>
    </html>
  )
}